services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    environment:
      POSTGRES_DB: sea_battle_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build:
      dockerfile: Dockerfile
    container_name: sea_battle_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sea_battle_db
      SPRING_PROFILES_ACTIVE: prod
      PORT: 8080
      DB_URL: jdbc:postgresql://postgres:5432/sea_battle_db
      DB_USERNAME: user
      DB_PASSWORD: password
      JWT_SECRET: AvaBwBD0xSg1ZlAop3WyS3XxdvjRJ9ezTAKjYQ0dak2
      REFRESH_TOKEN_EXPIRATION: 604800000
      ACCESS_TOKEN_EXPIRATION: 900000
      WEBSOCKET_ALLOWED_ORIGINS: *

volumes:
  postgres_data:
