spring.application.name=sea-battle
spring.datasource.url=jdbc:postgresql://localhost:5432/sea_battle_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=AvaBwBD0xSg1ZlAop3WyS3XxdvjRJ9ezTAKjYQ0dak2
refresh.token.expiration=604800000
access.token.expiration=900000
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN